drop index ASSOCIATION_9_FK IF EXISTS;

drop index ASSOCIATION_7_FK IF EXISTS;

drop index ASSOCIATION_7_PK IF EXISTS;

drop table IF EXISTS ASSOCIATION_7;

drop index IF EXISTS ASSOCIATION_11_FK;

drop index IF EXISTS ASSOCIATION_10_FK;

drop index IF EXISTS ASSOCIATION_9_PK;

drop table IF EXISTS ASSOCIATION_9;

drop index IF EXISTS DEVISE_PK;

drop table IF EXISTS DEVISE;

drop index IF EXISTS ASSOCIATION_8_FK;

drop index IF EXISTS ASSOCIATION_6_FK;

drop index IF EXISTS ASSOCIATION_5_FK;

drop index IF EXISTS EST_DEFINIE_PAR_FK;

drop index IF EXISTS ECRITURE_PK;

drop table IF EXISTS ECRITURE;

drop index IF EXISTS CREE_FK;

drop index IF EXISTS EVENEMENT_PK;

drop table IF EXISTS EVENEMENT;

drop index IF EXISTS EST_UN_FK;

drop index IF EXISTS PARTICIPANT_PK;

drop table IF EXISTS PARTICIPANT;

drop index IF EXISTS TYPE_ECRITURE_PK;

drop table IF EXISTS TYPE_ECRITURE;

drop index IF EXISTS EST_UN2_FK;

drop index IF EXISTS UTILISATEUR_PK;

drop table IF EXISTS UTILISATEUR;
