<!DOCTYPE html>
<html style="height: 100%" lang="fr">
<head>
    <meta charset="UTF-8">
</head>
<body style="display: flex;flex-direction: column;margin: 0;height:100%">
<header style="background-color: white;display: flex;justify-content: center;">
    <img style="max-width: 15%;margin: 2%" src="cid:header">
</header>
<main style="padding-top:2%;background-color: #2a92e8;color: white;display: flex;flex-direction: column;align-items: center;">
    <h1 style="font-family: 'Liberation Serif';margin-top: 2%">Bienvenue sur Tricount DA2I</h1>
    <div style="margin-top:2%;margin-bottom:2%;width: 50%;background-color: white;height: 2px"></div>
    <div style="font-family: 'helvetica neue';font-size: larger;display: flex;flex-direction: column;margin-top: 2%">
        <div style="width: 100%;min-height: 5%">Vous êtes bien enregistré sur l'application</div>
        <div style="margin-top: 5%">
            <div>Nom d'utilisateur : ${nom}</div>
        </div>
    </div>
    <div style="margin-top:2%;margin-bottom:2%;width: 50%;background-color: white;height: 2px"></div>
    <div style="display: flex;flex-direction: column;align-items: center;margin-top: 2%">
        <img width="30%" src="cid:iphone">
        <div style="font-family: 'helvetica neue';font-size: larger;margin-top: 5%;margin-bottom: 5%"><b>Tricount DA2I</b>, la solution facile pour faire les comptes entre amis</div>
    </div>
    <div style="margin-top:2%;margin-bottom:2%;width: 50%;background-color: white;height: 2px"></div>

</main>
<footer style="background-color: white;color: #2a92e8;display: flex;justify-content: center;align-items: center;min-height: 5%">
    <div>Vous avez reçu cet email car vous vous êtes inscrit sur l'application Tricount DA2i</div>
</footer>
</body>
</html>